name: Per-commit CI Test
on:
  push:
    branches:
    - main
    paths-ignore:
    - '.devcontainer/**'
    - '.docker/**'
    - '.github/**'
    - '.vscode/**'
  pull_request:
    branches:
    - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: [7.3, 7.4, 8.0, 8.1, 8.2, 8.3, 8.4]

    services:
      smtp_mock:
        image: mailhog/mailhog:latest
        ports:
        - 1025:1025

    steps:
      - uses: actions/checkout@v3

      - name: Composer Dependencies
        uses: php-actions/composer@v6
        with:
          dev: yes
          args: --profile --ignore-platform-reqs

      - name: Create .env Config
        run: |
          touch .env
          echo SMTP_HOST=localhost >> .env
          echo SMTP_AUTH=0 >> .env
          echo SMTP_USER= >> .env
          echo SMTP_PASS= >> .env
          echo SMTP_PORT=1025 >> .env
          echo SMTP_FROM=gh-unit@example.com >> .env
          echo realpath .env
          cat .env

      - name: Run PHPUnit
        run: vendor/bin/phpunit --configuration phpunit.xml --colors=always
        env:
          PHP_VERSION: ${{ matrix.php-version }}
